#!/bin/bash

set -eu -o pipefail
${DEBUGSH+set -x}

case "$1" in
	dependencies)
		echo build-dir
		;;
	run)
		echo "I am b!"
		sleep 3
		echo foo b > build/b
		;;
	is-done)
		[[ -f build/b ]] && echo yes || echo no
		;;
	*)
		>&2 echo "$0: Unexpected argument: $1"
		exit 1
		;;
esac

