#!/bin/bash

set -eu -o pipefail
${DEBUGSH+set -x}

case "$1" in
	dependencies)
		;;
	run)
		mkdir -p build
		;;
	is-done)
		[[ -d build ]] && echo yes || echo no
		;;
	*)
		>&2 echo "$0: Unexpected argument: $1"
		exit 1
		;;
esac

